config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'
  root to: 'pages#home'
  get 'pages/about'
  get 'pages/terms'
  get 'pages/privacy'
  get 'pages/contact'
  get 'pages/faq'
  get 'pages/site_map'
  
  post 'offerings/booking(/:id)', to: 'offerings#book', :as => 'offerings_booking'
  get 'offerings/bookings'
  get 'offerings/booking/:id/cancel', to: 'offerings#cancel', :as => 'offerings_booking_cancel'

  resources :offerings

  devise_for :users
  
  resources :courses do
    resources :posts do
      resources :comments
    end
  end

  get '/search' => 'courses#search', :as => 'search_page'
  get 'repos/search' => 'repos#search', :as => 'search_repo'
  post'courses/join_action', :as => 'join_course'
  
  resources :repos do
    resources :items do
      get :download_file
    end
    post :join_action
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/repo.rb
class Repo < ApplicationRecord
    has_many :items, dependent: :destroy
    has_and_belongs_to_many :users
    has_and_belongs_to_many :courses
    has_rich_text :description

    validates :name, :presence => true, :uniqueness => true, :length => { :in => 3..30 }
    validates :description, :presence => true
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :join_action]

    def index
        @repos = Repo.all
    end

    def show
        @repo = Repo.find(params[:id])
    end

    def new
        @courses = Course.all
        @courseList = []
        @courses.each do |e|
            @courseList << e.code
        end
        @repo = Repo.new
    end

    def edit
        @courses = Course.all
        @courseList = []
        @courses.each do |e|
            @courseList << e.code
        end
        @repo = Repo.find(params[:id])

    end

    def create
        @repo = Repo.new(repo_params)
        if @repo.save
            #adding the user to repo's user table
            @repo.users << current_user
            @course = Course.find_by(code: (params[:repo][:course_id]))
            @course.repos << @repo
            redirect_to @repo
        else
            render 'new'
        end
    end

    def update
        @repo = Repo.find(params[:id])

        if @repo.update(repo_params)
            redirect_to @repo
        else
            render 'edit'
        end
    end

    def destroy
        @repo = Repo.find(params[:id])
        @repo.destroy
        
        redirect_to repos_path
    end

    def search
        @repo = Repo.find_by(name: (params[:search])) 
        
        if @repo
            @users = User.all
            render "show"
        else
            @repos = Repo.all
            render "index"
        end
    end

    def join_action
        if (user_signed_in?)
            @repo = Repo.find(params[:repo_id])
            unless (@repo.users.include?(current_user))
                @repo.users << current_user
                @users = User.all
                redirect_to @repo
            end
        end
    end

    private
        def repo_params
            params.require(:repo).permit(:name, :description)
        end
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/repos/_form.html.erb
<div class="container repos-form">
  <div class="repos-image">
    <img src="https://image.ibb.co/kUagtU/rocket_contact.png" alt="rocket_contact" />
  </div>
  <%= form_with model: @repo, local: true do |form| %>
  <% if @repo.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@repo.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @repo.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <h3><%= formType %> a Repo</h3>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.text_field :name, :class=>"form-control", :placeholder=>"title"%>
      </div>
      <div class="form-group">

      </div>
      <div class="form-group">
        <%= form.select :course_id, @courseList, :class=>"form-control"%>
      </div>

    </div>
    <div class="col-md-12">
      <div class="form-group">
        <%= form.rich_text_area :description, class: "form-control", :placeholder=>"description" %>
      </div>
      <div class="form-group">
        <%= form.submit :class=>"btnContact" %>
        <%= link_to '<button type="button" class="btnBack">Back</button>'.html_safe, repos_path %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/repos/edit.html.erb
<%= render 'form', formType: "Edit"%>

app/views/repos/index.html.erb
<div id="repoIndex">
<div id="search_bar_repo">
<%= form_tag(search_repo_path, method: :get,id:"repos") do %>
  <%= text_field_tag(:search, params[:search], placeholder: 'Enter Repo Name', id: 'input_repo')%>
  <%=submit_tag('Search', id: 'submit_repo') %>
<% end %>
</div>

<%= link_to '<button type="button" class="btn btn-primary" id="repos">New Repo</button>'.html_safe, new_repo_path %>
<table id="repos">
  <tr>
    <th>Name</th>
    <th>Course</th>
    <th colspan="3"></th>
  </tr>
 
  <% @repos.each do |repo| %>
    <tr>
      <td><%= repo.name %></td>
      <td><%= repo.courses[0].code%></td>
      <td><%= link_to 'Show', repo_path(repo) %></td>
      <td><%= link_to 'Edit', edit_repo_path(repo) %></td>
      <td><%= link_to 'Destroy', repo_path(repo),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

</div>

app/views/repos/new.html.erb
<%= render 'form' , formType: "Create"%>

app/views/repos/show.html.erb
<div class="container1">
<div id="repo">
  <div id="repo_body">
    <div id="repo_name">
      <p>
        <strong>
          <font size=6em><%= @repo.name %></font>

        </strong>

      </p>
    </div>
    <p>
      <%=link_to 'Edit Repo', edit_repo_path(@repo) %>
    </p>
    <p>
      <font size=4em><%= link_to @repo.courses[0].code, @repo.courses[0] %></font>
    </p>
    <p>
      <strong>Description:</strong>
      <%= @repo.description %>
    </p>


  </div>
    
  <% if !@repo.users.include?(current_user)%>
  <%= link_to '<button type="button" class="btn btn-primary" id="repos">Join</button>'.html_safe, repo_join_action_path(@repo), method: "post" %>
  <% else %>
  <p> You are a member of this repository. </p>
  <% end %>
  <table id="repos">
    <tr>
      <th>Name</th>
      <th>Show</th>
      <th>Download</th>
      <th>Delete</th>
    </tr>

    <% @repo.items.each do |item| %>
    <% if item.name != nil %>
    <tr>
      <td><%= item.name %></td>
      <td><%= link_to 'Show', repo_item_path(@repo, item) %></td>
      <td><%= link_to 'Download', repo_item_download_file_path(@repo, item) %></td>
      <td><%= link_to 'Destroy item', [item.repo, item],
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end%>
    <% end %>
  </table>


</div><br>

<div id ="upload">
<h2>Add items</h2></br>
<%= render 'items/form' %>
</div>
</div>