config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'
  root to: 'pages#home'
  get 'pages/about'
  get 'pages/terms'
  get 'pages/privacy'
  get 'pages/contact'
  get 'pages/faq'
  get 'pages/site_map'
  
  post 'offerings/booking(/:id)', to: 'offerings#book', :as => 'offerings_booking'
  get 'offerings/bookings'
  get 'offerings/booking/:id/cancel', to: 'offerings#cancel', :as => 'offerings_booking_cancel'

  resources :offerings

  devise_for :users
  
  resources :courses do
    resources :posts do
      resources :comments
    end
  end

  get '/search' => 'courses#search', :as => 'search_page'
  get 'repos/search' => 'repos#search', :as => 'search_repo'
  post'courses/join_action', :as => 'join_course'
  
  resources :repos do
    resources :items do
      get :download_file
    end
    post :join_action
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/offering.rb
class Offering < ApplicationRecord
    belongs_to :organizer, class_name: "User"
    belongs_to :attendee, class_name: "User"
    has_rich_text :description
end

app/controllers/offerings_controller.rb
class OfferingsController < ApplicationController
    skip_before_action :verify_authenticity_token

    def index
        @offerings = Offering.all
    end

    def new
        @offering = Offering.new
    end

    def create
        address = [offering_params[:street], offering_params[:city], offering_params[:province], offering_params[:country]].compact.join(', ')
        results = Geocoder.search(address)
        puts address
        puts results.first.coordinates[0]
        puts results.first.coordinates[1]


        offering_params_2 = {}
        offering_params_2[:title] = offering_params[:title]
        offering_params_2[:course_id] = offering_params[:course_id]
        offering_params_2[:cost] = offering_params[:cost]
        offering_params_2[:description] = offering_params[:description]
        offering_params_2["startTime(1i)"] = offering_params["startTime(1i)"]
        offering_params_2["startTime(2i)"] = offering_params["startTime(2i)"]
        offering_params_2["startTime(3i)"] = offering_params["startTime(3i)"]
        offering_params_2["startTime(4i)"] = offering_params["startTime(4i)"]
        offering_params_2["startTime(5i)"] = offering_params["startTime(5i)"]
        offering_params_2["endTime(1i)"] = offering_params["endTime(1i)"]
        offering_params_2["endTime(2i)"] = offering_params["endTime(2i)"]
        offering_params_2["endTime(3i)"] = offering_params["endTime(3i)"]
        offering_params_2["endTime(4i)"] = offering_params["endTime(4i)"]
        offering_params_2["endTime(5i)"] = offering_params["endTime(5i)"]
        offering_params_2[:street] = offering_params[:street]
        offering_params_2[:city] = offering_params[:city]
        offering_params_2[:province] = offering_params[:province]
        offering_params_2[:country] = offering_params[:country]
        offering_params_2[:address] = address
        offering_params_2[:latitude] = results.first.coordinates[0]
        offering_params_2[:longitude] = results.first.coordinates[1]
        offering_params_2[:organizer] = User.find(current_user.id)
        # For now set the attendee to yourself
        # We can also add 'optional: true' for this foreign key in offerings model
        offering_params_2[:attendee] = offering_params_2[:organizer]

        @offering = Offering.new(offering_params_2)

        if @offering.save
            redirect_to @offering
        else
            render 'new'
        end
    end

    def show
        @offering = Offering.find(params[:id])
        @offering_startTime = @offering.startTime.in_time_zone("Eastern Time (US & Canada)")
        @offering_endTime = @offering.endTime.in_time_zone("Eastern Time (US & Canada)")
    end

    def book
        @offering = Offering.find(params[:id])

        # Book the offering
        @offering.update_attribute(:attendee, User.find(current_user.id))
        @offering.update_attribute(:status, "Booked")

        OfferingMailer.with(user: User.find(@offering.organizer_id), offering: @offering).booking_email.deliver_now
        OfferingMailer.with(user: current_user, offering: @offering).booking_email.deliver_now

        redirect_to @offering
    end

    def bookings
        @offerings = Offering.all
    end

    def edit
        @offering = Offering.find(params[:id])
    end

    def update
        @offering = Offering.find(params[:id])
        address = [offering_params[:street], offering_params[:city], offering_params[:province], offering_params[:country]].compact.join(', ')
        results = Geocoder.search(address)

        offering_params_2 = {}
        offering_params_2[:course_id] = offering_params[:course_id]
        offering_params_2[:cost] = offering_params[:cost]
        offering_params_2[:description] = offering_params[:description]
        offering_params_2["startTime(1i)"] = offering_params["startTime(1i)"]
        offering_params_2["startTime(2i)"] = offering_params["startTime(2i)"]
        offering_params_2["startTime(3i)"] = offering_params["startTime(3i)"]
        offering_params_2["startTime(4i)"] = offering_params["startTime(4i)"]
        offering_params_2["startTime(5i)"] = offering_params["startTime(5i)"]
        offering_params_2["endTime(1i)"] = offering_params["endTime(1i)"]
        offering_params_2["endTime(2i)"] = offering_params["endTime(2i)"]
        offering_params_2["endTime(3i)"] = offering_params["endTime(3i)"]
        offering_params_2["endTime(4i)"] = offering_params["endTime(4i)"]
        offering_params_2["endTime(5i)"] = offering_params["endTime(5i)"]
        offering_params_2[:address] = address
        offering_params_2[:latitude] = results.first.coordinates[0]
        offering_params_2[:longitude] = results.first.coordinates[1]
        offering_params_2[:organizer] = User.find(current_user.id)
        # For now set the attendee to yourself
        # We can also add 'optional: true' for this foreign key in offerings model
        offering_params_2[:attendee] = offering_params_2[:organizer]

        if @offering.update(offering_params_2)
            redirect_to @offering
        else
            render 'edit'
        end
    end

    def destroy
        @offering = Offering.find(params[:id])
        @offering.destroy

        redirect_to offerings_path
    end

    def cancel
        @offering = Offering.find(params[:id])

        @offering.update_attribute(:status, "Free")

        redirect_to @offering
    end

    private
        def offering_params
            params.require(:offering).permit(:title, :description, :course_id, :cost, :startTime, :endTime, :street, :city, :province, :country)
        end

end

app/views/offerings/_form.html.erb
<%= form_with model: @offering, local: true do |f| %>
<% if @offering.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@offering.errors.count, "error") %> prohibited
    this article from being saved:
  </h2>
  <ul>
    <% @offering.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class = "offerings_page application_background_color">
<div id="offer_tutor">
<h1><%= formType %> Service</h1><br>


  <form>
    <div class="form-row">

      <div class="form-group col-md-12">
        <strong> <%= f.label "title:" %></strong><br>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group col-md-6">
        <strong><%= f.label "Course code and name: " %> </strong><br>
        <%= f.collection_select :course_id, Course.all, :id, lambda {|u| "#{u.code} - #{u.name}"}, {:prompt => "Please select course"} , class: "form-control"%><br>
      </div>
      <div class="form-group col-md-6">
        <strong><%= f.label "Cost ($)" %></strong><br>
        <%= f.number_field :cost, min: 0, step: 0.01 , class: "form-control"%>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <strong><%= f.label "Start time:" %></strong><br>
        <%= f.datetime_select :startTime, class: "form-control"%>

      </div>
      <div class="form-group col-md-6">
        <strong> <%= f.label "End time:" %> </strong><br>
        <%= f.datetime_select :endTime, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <strong><%= f.label "Street address:" %></strong><br>
      <%= f.text_field :street , class: "form-control"%>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <strong> <%= f.label :city %></strong><br>
        <%= f.text_field :city, class: "form-control" %>
      </div>
      <div class="form-group col-md-4">
        <strong> <%= f.label :province %></strong><br>
        <%= f.text_field :province, class: "form-control" %>
      </div>
      <div class="form-group col-md-2">
        <strong> <%= f.label :country %></strong><br>
        <%= f.text_field :country, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <strong> <%= f.label :description %></strong>
      <%= f.rich_text_area :description, class: "form-control" %>
    </div>

    <%= f.submit :class=>"btn btn-primary",:id=>"submit", :method => "edit"%>
  </form>
</div>
</div>

<% end %>

app/views/offerings/bookings.html.erb
<div class="tables-container">

    <div class="table-container">
        <a data-toggle="collapse" href="#my_offering" role="button" aria-expanded="false" aria-controls="collapseExample" class = "collapse_toggle course_link">
        <h1 >My Offerings</h1>
        </a>
        <table class = "collapse show" id="my_offering">
            <tr>
                <th>Organizer</th>
                <th>Attendee</th>
                <th>Course</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Location</th>
                <th>Status</th>
                <th colspan="2"></th>
            </tr>

            <% @offerings.order(:created_at).reverse.each do |offering| %>
            <% if current_user && current_user.id == offering.organizer.id && Time.current.in_time_zone("Eastern Time (US & Canada)") <= offering.startTime.in_time_zone("Eastern Time (US & Canada)") %>
            <tr>
                <td><%= link_to "#{User.find(offering.organizer.id).user_name}", users_profile_path(User.find(offering.organizer.id)), :class => "post_links"%>
                </td>
                <% if offering.status == "Free" %>
                <td> N/A </td>
                <% else %>
                <td><%= link_to "#{User.find(offering.attendee.id).user_name}", users_profile_path(User.find(offering.attendee.id)), :class => "post_links"%>
                </td>
                <% end %>
                <td><%= Course.find(offering.course_id).code %> - <%= Course.find(offering.course_id).name %></td>
                <td><%= offering.startTime.in_time_zone("Eastern Time (US & Canada)").year %>-<%= offering.startTime.in_time_zone("Eastern Time (US & Canada)").month %>-<%= offering.startTime.in_time_zone("Eastern Time (US & Canada)").day %>
                    <%= offering.startTime.in_time_zone("Eastern Time (US & Canada)").hour %>:<%= offering.startTime.in_time_zone("Eastern Time (US & Canada)").min %>
                </td>
                <td><%= offering.endTime.in_time_zone("Eastern Time (US & Canada)").year %>-<%= offering.endTime.in_time_zone("Eastern Time (US & Canada)").month %>-<%= offering.endTime.in_time_zone("Eastern Time (US & Canada)").day %>
                    <%= offering.endTime.in_time_zone("Eastern Time (US & Canada)").hour %>:<%= offering.endTime.in_time_zone("Eastern Time (US & Canada)").min %>
                </td>
                <td><%= offering.address %></td>
                <td><%= offering.status %></td>
                <td><%= link_to "Show", offering_path(offering.id), :class => "post_link"%></td>
            </tr>
            <% end %>
            <% end %>

            
        </table>
    </div><br>
    <div class="table-container">
    <a data-toggle="collapse" href="#my_booking" role="button" aria-expanded="false" aria-controls="collapseExample" class = "collapse_toggle course_link">
        <h1 >My Bookings</h1>
    </a>
    <table  class ="collapse show" id="my_booking">
        <tr>
            <th>Organizer</th>
            <th>Attendee</th>
            <th>Course</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Location</th>
            <th>Status</th>
            <th colspan="2"></th>
        </tr>
        <% @offerings.order(:created_at).reverse.each do |offering| %>
        <% if current_user && current_user.id == offering.attendee.id && offering.status == "Booked" && Time.current.in_time_zone("Eastern Time (US & Canada)") <= offering.startTime.in_time_zone("Eastern Time (US & Canada)") %>
        <tr>
            <td><%= link_to "#{User.find(offering.organizer.id).user_name}", users_profile_path(User.find(offering.organizer.id)), :class => "post_links"%>
            </td>
            <td><%= link_to "#{User.find(offering.attendee.id).user_name}", users_profile_path(User.find(offering.attendee.id)), :class => "post_links"%>
            </td>
            <td><%= Course.find(offering.course_id).code %> - <%= Course.find(offering.course_id).name %></td>
            <td><%= offering.startTime.in_time_zone("Eastern Time (US & Canada)").year %>-<%= offering.startTime.in_time_zone("Eastern Time (US & Canada)").month %>-<%= offering.startTime.in_time_zone("Eastern Time (US & Canada)").day %>
                <%= offering.startTime.in_time_zone("Eastern Time (US & Canada)").hour %>:<%= offering.startTime.in_time_zone("Eastern Time (US & Canada)").min %>
            </td>
            <td><%= offering.endTime.in_time_zone("Eastern Time (US & Canada)").year %>-<%= offering.endTime.in_time_zone("Eastern Time (US & Canada)").month %>-<%= offering.endTime.in_time_zone("Eastern Time (US & Canada)").day %>
                <%= offering.endTime.in_time_zone("Eastern Time (US & Canada)").hour %>:<%= offering.endTime.in_time_zone("Eastern Time (US & Canada)").min %>
            </td>
            <td><%= offering.address %></td>
            <td><%= offering.status %></td>
            <td><%= link_to "Show", offering_path(offering.id), :class => "post_link"%></td>
        </tr>
        <% end %>
        <% end %>
    </table>
</div>
</div>

app/views/offerings/edit.html.erb
<%= render 'form', offering: @offering, formType: "Edit"%>

app/views/offerings/index.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
  $("#input").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#row tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>

<script>
function sortTable(n) {
  var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
  table = document.getElementById("offering");
  switching = true;
  // Set the sorting direction to ascending:
  dir = "asc";
  /* Make a loop that will continue until
  no switching has been done: */
  while (switching) {
    // Start by saying: no switching is done:
    switching = false;
    rows = table.rows;
    /* Loop through all table rows (except the
    first, which contains table headers): */
    for (i = 1; i < (rows.length - 1); i++) {
      // Start by saying there should be no switching:
      shouldSwitch = false;
      /* Get the two elements you want to compare,
      one from current row and one from the next: */
      x = rows[i].getElementsByTagName("TD")[n];
      y = rows[i + 1].getElementsByTagName("TD")[n];
      /* Check if the two rows should switch place,
      based on the direction, asc or desc: */
      if (dir == "asc") {
        if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
          // If so, mark as a switch and break the loop:
          shouldSwitch = true;
          break;
        }
      } else if (dir == "desc") {
        if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
          // If so, mark as a switch and break the loop:
          shouldSwitch = true;
          break;
        }
      }
    }
    if (shouldSwitch) {
      /* If a switch has been marked, make the switch
      and mark that a switch has been done: */
      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
      switching = true;
      // Each time a switch is done, increase this count by 1:
      switchcount ++;
    } else {
      /* If no switching has been done AND the direction is "asc",
      set the direction to "desc" and run the while loop again. */
      if (switchcount == 0 && dir == "asc") {
        dir = "desc";
        switching = true;
      }
    }
  }
}
</script>

<div>
<div class = "application_background_color offerings_page">
<div class = "table-container ">
<h1 >Offerings</h1>
<input id="input" type="text" placeholder="Search for course, tutor, availability, etc..." style="width: 800px;">
<table id="offering">
  <tr>
    <th onclick="sortTable(0)">Organizer</th>
    <th onclick="sortTable(1)">Title</th>
    <th onclick="sortTable(2)">Courses</th>
    <th onclick="sortTable(3)">Start Time</th>
    <th onclick="sortTable(4)">End Time</th>
    <th onclick="sortTable(5)">Address</th>
    <th onclick="sortTable(6)">Cost</th>
    <th onclick="sortTable(7)">Availability</th>
    <th colspan="2"></th>
  </tr>

  <% @offerings.order(:created_at).reverse.each do |offering| %>
    <% if current_user && Time.current.in_time_zone("Eastern Time (US & Canada)") <= offering.startTime.in_time_zone("Eastern Time (US & Canada)") %>
      <tbody id="row">
        <tr>
          <td><%= link_to "#{User.find(offering.organizer.id).user_name}", users_profile_path(User.find(offering.organizer.id)), :class => "post_links"%></td>
          <td><%= offering.title%></td>
          <td><%= Course.find(offering.course_id).code %> - <%= Course.find(offering.course_id).name %></td>
          <td><%= offering.startTime.in_time_zone("Eastern Time (US & Canada)").year %>-<%= offering.startTime.in_time_zone("Eastern Time (US & Canada)").month %>-<%= offering.startTime.in_time_zone("Eastern Time (US & Canada)").day %>
          <%= offering.startTime.in_time_zone("Eastern Time (US & Canada)").hour %>:<%= offering.startTime.in_time_zone("Eastern Time (US & Canada)").min %></td>
          <td><%= offering.endTime.in_time_zone("Eastern Time (US & Canada)").year %>-<%= offering.endTime.in_time_zone("Eastern Time (US & Canada)").month %>-<%= offering.endTime.in_time_zone("Eastern Time (US & Canada)").day %>
          <td><%= offering.address %></td>
          <td>$<%= offering.cost %></td>
          <td><%= offering.status %></td>
          <td><%= link_to "Show", offering_path(offering.id), :class => "post_link"%></td>
        </tr>
      </tbody>
    <% end %>
  <% end %>
  </table>
</div>
</div>
</div>

app/views/offerings/new.html.erb
<%= render 'form', offering: @offering, formType: "New" %>

app/views/offerings/show.html.erb
<div class="tables-container">
<div class="table-container">

<h1 class = "show_booking_title_spacing"> 
  <%=Course.find(@offering.course_id).code %>: <%=@offering.title%>
  </h1>
<p>
  <strong>Course:</strong>
  <%= link_to "#{Course.find(@offering.course_id).code} - #{Course.find(@offering.course_id).name}", course_path(Course.find(@offering.course_id)), :class => "post_links"%>
</p>

<p>
  <strong>Organizer:</strong>
  <%= link_to "#{User.find(@offering.organizer.id).user_name}", users_profile_path(User.find(@offering.organizer.id)), :class => "post_links"%>
</p>

<p>
  <strong>Attendee:</strong>
  <% if @offering.status != "Free" %>
  <%= link_to "#{User.find(@offering.attendee.id).user_name}", users_profile_path(User.find(@offering.attendee.id)), :class => "post_links"%>
  <% else %>
  N/A
  <% end %>
</p>

<p>
  <strong>Address:</strong>
  <%= @offering.address %>
</p>

<p>
  <strong>Cost:</strong>
  $<%= @offering.cost %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @offering_startTime.year %>-<%= @offering_startTime.month %>-<%= @offering_startTime.day %>
  <%= @offering_startTime.hour %>:<%= @offering_startTime.min %>
</p>

<p>
  <strong>End time:</strong>
  <%= @offering_endTime.year %>-<%= @offering_endTime.month %>-<%= @offering_endTime.day %>
  <%= @offering_endTime.hour %>:<%= @offering_endTime.min %>
</p>

<p>
  <strong>Details:</strong>
  <%= @offering.description %>
</p>

<p>
<strong>Status:</strong>
<%= @offering.status %>
</p>

<% if current_user.id != @offering.organizer.id &&  @offering.status == "Free"%>
  <%= form_tag offerings_booking_path(@offering) do %>
      <article>
      <% if flash[:error].present? %>
      <div id="error_explanation">
      <p><%= flash[:error] %></p>
      </div>
      <% end %>
      <label class="amount">
      <span>Amount: <%= @offering.cost %></span>
      </label>
      </article>
      
      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="pk_test_uwGWFCOkmQqwcOPWQGHqkwGY00jnWfhTkH"
      data-description="Tutoring Payment"
      data-amount="<%= @offering.cost * 100 %>"
      data-locale="auto"></script>
  <% end %>
<% end %>

<div style='width:100%; height:100%;'>  
  <div id="map" style='width: 800px; height: 400px;'></div>  
</div>  <br>

<% if current_user && current_user.id == @offering.organizer.id %>
  <%= link_to 'Edit', edit_offering_path(@offering),:class => "btn btn-secondary", :form_class => "login_buton_form"  %>
  <%= link_to 'Delete', offering_path(@offering), method: "delete", :data => { confirm: 'Are you sure?' }, :class => "btn btn-primary", :id=>"delete",:form_class => "login_buton_form"  %>
<% elsif current_user.id == @offering.attendee.id && @offering.status != "Free" %>
  <%= link_to 'Cancel Booking', offerings_booking_cancel_path(@offering), :method => "get",:class => "btn btn-secondary", :form_class => "login_buton_form"  %>
<% end %>

<script type="text/javascript">  
handler = Gmaps.build('Google');

handler.buildMap({ provider: {}, internal: {id: 'map'}, map_options: {}}, function(){  
  markers = handler.addMarkers([  
    {  
      "lat": <%= @offering.latitude %>,  
      "lng": <%= @offering.longitude %>,  
      "picture": {  
        "width":  32,  
        "height": 32
      },  
      "infowindow": "<%= @offering.address %>"
    }  
  ]);  
  handler.bounds.extendWith(markers);  
  handler.fitMapToBounds();
  handler.getMap().setZoom(17);
});  
</script>
</div>
</div>