config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'
  root to: 'pages#home'
  get 'pages/about'
  get 'pages/terms'
  get 'pages/privacy'
  get 'pages/contact'
  get 'pages/faq'
  get 'pages/site_map'
  
  post 'offerings/booking(/:id)', to: 'offerings#book', :as => 'offerings_booking'
  get 'offerings/bookings'
  get 'offerings/booking/:id/cancel', to: 'offerings#cancel', :as => 'offerings_booking_cancel'

  resources :offerings

  devise_for :users
  
  resources :courses do
    resources :posts do
      resources :comments
    end
  end

  get '/search' => 'courses#search', :as => 'search_page'
  get 'repos/search' => 'repos#search', :as => 'search_repo'
  post'courses/join_action', :as => 'join_course'
  
  resources :repos do
    resources :items do
      get :download_file
    end
    post :join_action
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    before_action :authenticate_user!, only: [:join_action]

    def index
        @courses = Course.all
    end

    def show
        @posts = Post.all
        # Get course
        @course = Course.find(params[:id])
        @users = User.all
    end

    def search
        @course = Course.find_by(code: (params[:search]).upcase) 
        
        if @course
            @users = User.all
            render "show"
        else
            @courses = Course.all
            render "index"
        end
    end

    def join_action
        if (user_signed_in?)
            @course = Course.find(params[:course_id])
            unless (@course.users.include?(current_user))
                @course.users << current_user
                @users = User.all
                redirect_to @course
            end
        end
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/index.html.erb
<div class = "course_index">

<div id="search_bar_course">
<%= form_tag(search_page_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search], placeholder: 'Enter Course Code', id: 'input_course')%>
  <%=submit_tag('Search', id: 'submit_course') %>
<% end %>
</div>

<div class="course_list_container">
  <a data-toggle="collapse" href="#collapse_first_year" role="button" aria-expanded="false" aria-controls="collapseExample" class = "collapse_toggle">
      <strong>First Year courses </strong>
  </a>
  <div class ="line_break"></div>
  <div class ="collapse show" id = "collapse_first_year">
  <table id="courses">
    <% @courses.where('year = 1').each do |course| %>
      <tr>
        <td><%= course.code %> <%= course.name %></td>
        <td><%= link_to 'Show', course_path(course), :class => "course_list_show"%></td>
      </tr>
    <% end %>
  </table>
  </div>
</div>

<div class="course_list_container">
  <a data-toggle="collapse" href="#collapse_second_year" role="button" aria-expanded="false" aria-controls="collapseExample" class = "collapse_toggle">
      <strong>Second Year courses </strong>
  </a>
  <div class ="line_break"></div>
  <div class ="collapse show" id = "collapse_second_year">
  <table id="courses">
    <% @courses.where('year = 2').each do |course| %>
      <tr>
        <td><%= course.code %> <%= course.name %></td>
        <td><%= link_to 'Show', course_path(course), :class => "course_list_show"%></td>
      </tr>
    <% end %>
  </table>
  </div>
</div>

<div class="course_list_container">
  <a data-toggle="collapse" href="#collapse_third_year" role="button" aria-expanded="false" aria-controls="collapseExample" class = "collapse_toggle">
      <strong>Third Year courses </strong>
  </a>
  <div class ="line_break"></div>
  <div class ="collapse show" id = "collapse_third_year">
  <table id="courses">
    <% @courses.where('year = 3').each do |course| %>
      <tr>
        <td><%= course.code %> <%= course.name %></td>
        <td><%= link_to 'Show', course_path(course), :class => "course_list_show"%></td>
      </tr>
    <% end %>
  </table>
  </div>
</div>

<div class="course_list_container">
  <a data-toggle="collapse" href="#collapse_fourth_year" role="button" aria-expanded="false" aria-controls="collapseExample" class = "collapse_toggle">
      <strong>Fourth Year courses </strong>
  </a>
  <div class ="line_break"></div>
  <div class ="collapse show" id = "collapse_fourth_year">
  <table id="courses">
    <% @courses.where('year = 4').each do |course| %>
      <tr>
        <td><%= course.code %> <%= course.name %></td>
        <td><%= link_to 'Show', course_path(course), :class => "course_list_show"%></td>
      </tr>
    <% end %>
  </table>
  </div>
</div>

app/views/courses/show.html.erb
<div class = "course_header">
  <%= image_tag ("default-course-header.png"), :class => "default_header_image"%>
  <h2 class = "course_title"><%= @course.code %> <%= @course.name %></h2>
</div>

<div class = "course_page">
  <div class = "course_page_lower_container">
    <div class = "course_page_container">
    
      <div class = "course_page_left_container">
        <% if @course.posts.count == 0 %>
          <div class = "course_post">
            <div class = "post_header">
                  <div><h5 class = "course_title create_first_post_title">
                  <%= link_to new_course_post_path(@course), :class => "post_link" do%>
                    Create First Post!
                  <% end %>
                  </h5></div>
              </div>
            
            </div>
          </div>
        <% end %>

        <% @course.posts.order(:created_at).reverse.each do |post| %>
          <div class = "course_post">
            <div>
                <div class = "post_header">
                  <div><h5 class = "course_title"> <%= link_to "#{post.category+'-'+post.title}", course_post_path(post.course, post), :class => "post_link" %></h5></div>
                  <div>Posted by user: <strong><%= link_to "#{@users.find(post.user_id).user_name}", users_profile_path(@users.find(post.user_id)), :class => "post_links"%> </strong></div>
                </div>
                <div class = "line_break"> </div>
                <div class ="post_description_container">
                <%= post.description%>
                </div>
            </div>
          </div>
        <% end %>

      </div>
      </div>

  <div class = "course_page_right_container">
  <div class = "course_right_sub_container">
  <div class = "course_right_info_container">
  <h4 class = "course_title"> <%= @course.code %> <%= @course.name %> </h4>
  <div class = "line_break"> </div>
  <%= @course.description %>
  </div>
    <% if !@course.users.include?(current_user)%>
      <div class = "back_button_container">
      <%= button_to 'Join', join_course_path(:course_id => @course), :class => "button", :form_class => "button_to"%>
      <!-- <%= button_to 'BACK', courses_path, :method => "get", :class => "button", :form_class => "button_to" %> -->
      </div>
    <% else %>
    <div class = "course_right_info_container">
      <%= button_to 'Create Post', new_course_post_path(@course), :method => "get", :class => "create_post_repo_button", :form_class => "button_to create_post_repo_button_container" %>
      <%= button_to 'Create repo', new_repo_path(:course_id => @course), :method => "get", :class => "create_post_repo_button", :form_class => "button_to create_post_repo_button_container" %>
    </div>
    <% end %>
    </div>

    <div class = "course_right_sub_container">
    <div class = "course_right_info_container">
      <h4 class = "course_title">Open Services</h4>
      <div class = "line_break"> </div>
      <% if Offering.where(course_id: @course.id).any?%>
      <% Offering.where(course_id: @course.id).each_with_index do |o,index| %>
        <% if o.status == "Free"%>
          <div>
              <div class = "post_header">
                <%= link_to "#{o.title}", offering_path(o.id) %> 
              </div>
              
          </div>
        <% end %>
      <% end %>
      <% else %>
        No open offering
      <% end %>
    </div>
    </div>

    <div class = "course_right_sub_container">
    <div class = "course_right_info_container">
      <h4 class = "course_title">Public Repos</h4>
      <div class = "line_break"> </div>
      <% if @course.repos.any?%>
      <% @course.repos.each do |r| %>
      <div>
          <div class = "post_header">
            <%= link_to r.name, r %>
          </div>
      </div>
      <% end %>
      <% else %>
        No public repos
      <% end %>

    </div>
    </div>

  </div>
  </div>

</div>