config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'
  root to: 'pages#home'
  get 'pages/about'
  get 'pages/terms'
  get 'pages/privacy'
  get 'pages/contact'
  get 'pages/faq'
  get 'pages/site_map'
  
  post 'offerings/booking(/:id)', to: 'offerings#book', :as => 'offerings_booking'
  get 'offerings/bookings'
  get 'offerings/booking/:id/cancel', to: 'offerings#cancel', :as => 'offerings_booking_cancel'

  resources :offerings

  devise_for :users
  
  resources :courses do
    resources :posts do
      resources :comments
    end
  end

  get '/search' => 'courses#search', :as => 'search_page'
  get 'repos/search' => 'repos#search', :as => 'search_repo'
  post'courses/join_action', :as => 'join_course'
  
  resources :repos do
    resources :items do
      get :download_file
    end
    post :join_action
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
    has_rich_text :description
    
    validates :description, :presence => true
end

app/models/course.rb
class Course < ApplicationRecord
    # Changed to many to many relationship
    # has_many :repos
    has_and_belongs_to_many :repos
    has_many :posts
    has_and_belongs_to_many :users

    validates :name, :presence => true, :length => { :in => 3..30 }
    validates :description, :presence => true
    validates :code, :presence => true
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :repo
    has_rich_text :description
    has_one_attached :file

    validates :name, :presence => true
    validates :url, :presence => true
    validates :description, :presence => true 
end

app/models/offering.rb
class Offering < ApplicationRecord
    belongs_to :organizer, class_name: "User"
    belongs_to :attendee, class_name: "User"
    has_rich_text :description
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    belongs_to :course
    belongs_to :user
    has_rich_text :description

    validates :title, :presence => true, :uniqueness => true, :length => { :in => 3..30 }
    validates :description, :presence => true
    # validates :category, :presence => true
end

app/models/repo.rb
class Repo < ApplicationRecord
    has_many :items, dependent: :destroy
    has_and_belongs_to_many :users
    has_and_belongs_to_many :courses
    has_rich_text :description

    validates :name, :presence => true, :uniqueness => true, :length => { :in => 3..30 }
    validates :description, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
    has_many :comments
    has_many :posts
    has_and_belongs_to_many :repos
    has_and_belongs_to_many :courses
    has_one_attached :file

    has_many :organizers, :class_name => "Offering", :foreign_key => "organizer"
    has_many :attendees, :class_name => "Offering", :foreign_key => "attendee"

    # attr_accessor :password //This will prevent the password from being saved

    # validates :name, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
    # validates :age, :numericality => { :only_integer => true }
    # validates :age, numericality: { greater_than: 15, less_than: 100 }
    # validates :email, :presence => true, :uniqueness => true, format: { with: URI::MailTo::EMAIL_REGEXP } 
    # validates :password, :confirmation => true #password_confirmation attr   #this is for confirming the password 
    # validates_length_of :password, :in => 6..20, :on => :create

    # before_save :encrypt_password
    # after_save :clear_password

    # def encrypt_password
    #     self.salt = BCrypt::Engine.generate_salt
    #     self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
    # end

    # def clear_password
    #     self.password = nil
    # end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def create
        @repo = Repo.find(params[:repo_id])

        # Hack for active storage
        item_params_2 = item_params
        file = item_params[:url]
        filename = item_params[:url].original_filename
        item_params_2[:file] = file
        item_params_2[:url] = filename

        upload_file
        # params[:item][:url] = params[:item][:url].original_filename

        @item = @repo.items.create(item_params_2)
        redirect_to repo_path(@repo)
    end

    def show
        @repo = Repo.find(params[:repo_id])
        @item = @repo.items.find(params[:id])
    end

    def upload_file
        uploaded_file = params[:item][:url]
        File.open(Rails.root.join('private', 'uploads', 
                uploaded_file.original_filename), 'wb') do |file|
            file.write(uploaded_file.read)
        end
    end

    def download_file
        @repo = Repo.find(params[:repo_id])
        @item = @repo.items.find(params[:item_id])

        send_file "#{Rails.root}/private/uploads/#{@item.url}",
                  filename: @item.url
    end

    def destroy
        @repo = Repo.find(params[:repo_id])
        @item = @repo.items.find(params[:id])
        delete_file
        @item.destroy
        redirect_to repo_path(@repo)
    end

    def delete_file
        path_to_file = Rails.root.join('private', 'uploads', @item.url)
        File.delete(path_to_file) if File.exist?(path_to_file)
    end

    private
        def item_params
            params.require(:item).permit(:name, :description, :url)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def terms
  end

  def privacy
  end

  def faq
  end

  def site_map
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, only: [:new]

    def new
        @post = Post.new
        @course = Course.find(params[:course_id])
    end

    def edit
        @course = Course.find(params[:course_id])
        @post = @course.posts.find(params[:id])
    end

    def create
        @course = Course.find(params[:course_id])

        # Add current user id to the hash
        post_params_2 = post_params
        post_params_2[:user_id] = current_user.id

        @post = @course.posts.create(post_params_2)

        # Check if creating the post was successful
        if @post.id
            redirect_to course_post_path(@course, @post)
        else
            render 'new'
        end
    end

    def update
        @course = Course.find(params[:course_id])
        @post = @course.posts.find(params[:id])

        # Add current course and user id to the hash
        post_params_2 = post_params
        post_params_2[:course_id] = @course.id
        post_params_2[:user_id] = current_user.id

        if @post.update(post_params_2)
            redirect_to course_post_path(@course, @post)
        else
            render 'edit'
        end
      end

    def show
        @course = Course.find(params[:course_id])
        @post = @course.posts.find(params[:id])
        @users = User.all
    end

    def destroy
        @course = Course.find(params[:course_id])
        @post = @course.posts.find(params[:id])
        @post.destroy

        redirect_to course_path(@course)
    end

    private
        def post_params
            params.require(:post).permit(:title, :description, :category)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_devise_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class = "application_background_color">
  <head>
    <title>StudyBuddy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="//maps.google.com/maps/api/js?key=AIzaSyBWcZ7aMZFYSNDa_zIsOmouYNVkDYUprNM"></script>  
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>  
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <script src='//underscorejs.org/underscore-min.js' type='text/javascript'></script>
    <script src='//cdn.jsdelivr.net/gmaps4rails/2.1.2/gmaps4rails.js'> </script>
    <script src='//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js'> </script>
  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Study Buddy</a>
        <% if current_user %>
          <strong><%= current_user.user_name%> </strong>
          <% if current_user.file.attached? %>
            <%= image_tag current_user.file, :class => "nav_bar_image" %>
          <% else %>
            <%= image_tag ("default-user.png"), :class => "nav_bar_image"%>
          <% end %>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href=<%=root_path%>>Home
                    <span class="sr-only">(current)</span>
                  </a>
            </li>


          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          About<b class="caret"></b>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li ><%= link_to "About Us", pages_about_path,:class => "dropdown-item" %></li>
            <li><%= link_to "FAQ", pages_faq_path,:class => "dropdown-item" %></li>
            <li><%= link_to "Contact", pages_contact_path,:class => "dropdown-item" %></li>
            <li><%= link_to "Site map", pages_site_map_path,:class => "dropdown-item" %></li>
            <li><%= link_to "Terms of Use", pages_terms_path,:class => "dropdown-item" %></li>
          
          </ul>
          </li>

          <li>
          <a class="nav-link" href=<%=courses_path%>>Courses</a>
          </li>


          <li>
          <a class="nav-link" href=<%=repos_path%>>Repos</a>
          </li>

            <% if current_user %>
              <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Service <b class="caret"></b>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li ><%= link_to "All offerings", offerings_path,:class => "dropdown-item" %></li>
                <li><%= link_to "Offer service", new_offering_path,:class => "dropdown-item" %></li>
              </ul>
              </li>

              <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              User <b class="caret"></b>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to "Appointments", offerings_bookings_path,:class => "dropdown-item" %></li>
                <li ><%= link_to "Profile", users_profile_path,:class => "dropdown-item" %></li>
                <li><%= link_to "Logout", destroy_user_session_path,:class => "dropdown-item", :method => "delete" %></li>
              </ul>
              </li>

            <% else %>
              <li class="nav-item">
                <a class="nav-link" href=<%=new_user_session_path%>>Sign in</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href=<%=new_user_registration_path%>>Sign up</a>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>

</html>

app/views/pages/about.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
  </ol>
  <div class="carousel-inner">
    <!-- Slide One - Set the background image for this slide in the line below -->
    <div class="carousel-item active"
      style="background-image: url('https://www.sportsnet.ca/wp-content/uploads/2019/04/Luke-Walton-1040x572.jpg')">
      <div class="carousel-caption d-none d-md-block">
        <h2 class="display-4">Walton</h2>
      </div>
    </div>
    <!-- Slide Two - Set the background image for this slide in the line below -->
    <div class="carousel-item"
      style="background-image: url('https://images.newrepublic.com/a45682cb63e916b4b0fbcc82573f14a499d5a042.jpeg?w=1200&q=65&dpi=2.625&fm=pjpg&h=496')">
      <div class="carousel-caption d-none d-md-block">
        <h2 class="display-4">Charlie</h2>
      </div>
    </div>
    <!-- Slide Three - Set the background image for this slide in the line below -->
    <div class="carousel-item"
      style="background-image: url('https://static2.cbrimages.com/wordpress/wp-content/uploads/2018/12/death-note-L.jpg')">
      <div class="carousel-caption d-none d-md-block">
        <h2 class="display-4">Micah</h2>
      </div>
    </div>
    <!-- Slide Four - Set the background image for this slide in the line below -->
    <div class="carousel-item" style="background-image: url('https://i.imgur.com/sorr0C7.jpg')">
      <div class="carousel-caption d-none d-md-block">
        <h2 class="display-4">Erick</h2>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<!-- Page Content -->
<section class="py-5 application_background_color">
  <div class="container">
    <h1 class="display-4">Study Buddy</h1>
    <p class="lead">Everyone knows the struggle of having to understand the material being taught in class, study for
      upcoming tests, projects, etc. The basic idea behind this service is to help student with their studies by:</p>

    <div class = "points">
      <li>offering a repository of notes, explanations, helpful diagrams, links to helpful tutorial Web pages, etc.
        organized by term course subject;</li>
      <li>offering a service that helps organize and manage study groups; and</li>
      <li>offering a service to hire individuals (Buddies) to provide such services as tutoring, homework assistance,
        taking lecture notes etc.<br><br>
      </li>
      <li>Create and promote a relevant, powerful homework help program that responds to the needs of and appeals to
        today’s youth using tools already popular such as technology, the internet, texting, and style they are famaliar
        with (reddit style dashboard);</li>
      <li>Tap into the skills, time and energy of the best and brightest students to help peer students paid or unpaid,
        while sharpening the skills of the next generation of working professionals.</li>
      <li>Establish a platform that allows students to find and book a tutor more easily and conveniently</li>
      <br>
      <br>
    </div>

  </div>

</section>  

app/views/pages/contact.html.erb
<!-- Page Content -->
<section class="py-5 application_background_color contact_page">
  <div class="container contact_container">
    <h1 class="display-4">Contact us</h1>
    <p class="lead">For additional information, please <a
        href="mailto:zhihao.zhang@mail.utoronto.ca?subject=Mail from Study Buddy">Email Us</a> </p>
        <!-- Add icon library -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
        <p class="lead">Or find us at: 40 St George StToronto, Ontario, Canada, M5S 2E4 </p>
        <div style='width:100%; height:100%;'>  
            <div id="map" style='width: 800px; height: 400px;'></div>  
        </div>  <br>

        <!-- Add font awesome icons -->

        <div id="icons">
        <a href="https://www.facebook.com" class="fa fa-facebook"></a>
        <span>   </span>
        <a href="https://www.google.ca" class="fa fa-google"></a>
        <span>   </span>
        <a href="https://www.linkedin.com" class="fa fa-linkedin"></a>
        <span>   </span>
        <a href="https://www.instagram.com" class="fa fa-instagram"></a>
        </div>

  </div>

</section>

<script type="text/javascript">  
    handler = Gmaps.build('Google');

    handler.buildMap({ provider: {}, internal: {id: 'map'}, map_options: {}}, function(){  
    markers = handler.addMarkers([  
        {  
        "lat": 43.65977015,  
        "lng": -79.3972632658009,  
        "picture": {  
            "width":  32,  
            "height": 32
        },  
        "infowindow": "40 St George St, Toronto, Ontario, Canada"
        }  
    ]);  
    handler.bounds.extendWith(markers);  
    handler.fitMapToBounds();
    handler.getMap().setZoom(17);
    });  
</script>  

app/views/pages/contact_us.html.erb
<!-- Page Content -->
<section class="py-5 application_background_color">
  <div class="container">
    <h1 class="display-4">Contact us</h1>
    <p class="lead">For additional information, please <a
        href="mailto:zhihao.zhang@mail.utoronto.ca?subject=Mail from Study Buddy">Email Us</a> </p>
        <!-- Add icon library -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
        <!-- Add font awesome icons -->

        <div id="icons">
        <a href="https://www.facebook.com" class="fa fa-facebook"></a>
        <span>   </span>
        <a href="https://www.google.ca" class="fa fa-google"></a>
        <span>   </span>
        <a href="https://www.linkedin.com" class="fa fa-linkedin"></a>
        <span>   </span>
        <a href="https://www.instagram.com" class="fa fa-instagram"></a>
        </div>

        <p class="lead">Or find us at: 40 St George StToronto, Ontario, Canada, M5S 2E4 </p>
        <div style='width:100%; height:100%;'>  
            <div id="map" style='width: 800px; height: 400px;'></div>  
        </div>  <br>
  </div>

</section>

<script type="text/javascript">  
    handler = Gmaps.build('Google');

    handler.buildMap({ provider: {}, internal: {id: 'map'}, map_options: {}}, function(){  
    markers = handler.addMarkers([  
        {  
        "lat": 43.65977015,  
        "lng": -79.3972632658009,  
        "picture": {  
            "width":  32,  
            "height": 32
        },  
        "infowindow": "<%= @offering.address %>"
        }  
    ]);  
    handler.bounds.extendWith(markers);  
    handler.fitMapToBounds();
    handler.getMap().setZoom(17);
    });  
</script>  

app/views/pages/faq.html.erb
<!-- Page Content -->
<div class = "faq_page application_background_color">
<section class="py-5 faq_container">
  <div class="container">
    <strong><h1 class="display-4">FAQ</h1></strong>

    <p class="lead">How do I sign up?</p>
    <div class = "points">
        <li>Click on the sign up button at the top right corner, then confirm the email that gets sent to
        the email that you signed up with.</li>
        <br>
        <br>
    </div>

    <p class="lead">How do I find a course?</p>
    <div class = "points">
        <li>You can either search for a course code with the search bar on the home page or find the course
        in the course lists page. </li>
        <br>
        <br>
    </div>

    <p class="lead">Where do I find a tutor?</p>
    <div class = "points">
        <li>After you log in, go to the All Offerings page, which can be found at right side of the navigation
        bar at the top. There, you can search for tutoring session and book it. </li>
        <br>
        <br>
    </div>

    <p class="lead">How do I create a repository for a course?</p>
    <div class = "points">
        <li>You can create repository from a course page or by repos page, which can be access via 
        the navigation bar. </li>
        <br>
        <br>
    </div>

    <p class="lead">Where do I see all of the services that I have booked?</p>
    <div class = "points">
        <li>You can view all of your bookings by accessing Appointments page, which can be found
        on the right said of the navigation bar after you log in. </li>
        <br>
        <br>
    </div>
  </div>

</section>  
</div>

app/views/pages/home.html.erb
<!-- Course Search Bar -->
<div class = "home_page">
<div class = "logo">
    <figure><%= image_tag ("logo.png") %></figure>
</div>
<div id="search_bar_home">
<%= form_tag(search_page_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search], placeholder: 'Enter Course Name', id: 'input_home')%>
  <%=submit_tag('Search',id: 'submit_home') %>
  <%= button_to 'Course list', courses_path, :class => "button"%>

<% end %>
</div>
</div>

app/views/pages/privacy.html.erb
<!-- Course Search Bar -->
<div class = "home_page">
<div class = "logo">
    <figure><%= image_tag ("logo.png") %></figure>
</div>
<div id="search_bar_home">
<%= form_tag(search_page_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search], placeholder: 'Enter Course Name', id: 'input_home')%>
  <%=submit_tag('Search',id: 'submit_home') %>
  <%= button_to 'Course list', courses_path, :class => "button"%>

<% end %>
</div>
</div>

app/views/pages/site_map.html.erb
<!-- Page Content -->
<section class="py-5 application_background_color contact_page">
  <div class="container contact_container">
    <h1 class="display-4">Site Map</h1>
    <p class="lead">The following image presents our application site map:</p>
    <%= image_tag ("lofi-Page-2.png"), :class => "default_image"%>


</section>  